# Generated by cask-dotfile-generator
# Created by: @seethroughtrees
# https://github.com/seethroughtrees/brew-cask-dotfile-generator


install autoconf
install freetype
install gdbm
install ghostscript
install graphviz
install heroku
install heroku-toolbelt
install htop-osx
install hub
install imagemagick
install jpeg
install libevent
install libpng
install libssh
install libtiff
install libtool
install little-cms2
install memcached
install mono
install msgpack
install node
install openssl
install pcre
install phantomjs
install pkg-config
install postgresql
install qt
install rbenv
install readline
install redis
install ruby-build
install the-silver-searcher
install tmate
install tmux
install tree
install vim
install xz
install zsh
install zsh-completions
